import ContactButton from '@/components/ContactButton';
import Provider from '@/components/Provider';
import { SmoothScroll } from '@/components/SmoothScroll';
import ThemeManager from '@/components/ThemeManager';
import type { Metadata } from 'next';
import { Montserrat_Alternates } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat_Alternates({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark" suppressHydrationWarning={true}>
      <body
        className={`${montserrat.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <SmoothScroll>
          <Provider>{children}</Provider>
          {/* <LiftUpButton /> */}
          <ContactButton />
        </SmoothScroll>
      </body>
    </html>
  );
}
